// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/platform_health.proto

package platform_health

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_UNKNOWN       Status = 0
	Status_HEALTHY       Status = 1
	Status_UNHEALTHY     Status = 2
	Status_LOOP_DETECTED Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "HEALTHY",
		2: "UNHEALTHY",
		3: "LOOP_DETECTED",
	}
	Status_value = map[string]int32{
		"UNKNOWN":       0,
		"HEALTHY":       1,
		"UNHEALTHY":     2,
		"LOOP_DETECTED": 3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_platform_health_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_platform_health_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_platform_health_proto_rawDescGZIP(), []int{0}
}

type HealthCheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// components to check (empty = all); supports hierarchical paths like "system/subcomponent"
	Components    []string `protobuf:"bytes,1,rep,name=components,proto3" json:"components,omitempty"`
	Hops          []string `protobuf:"bytes,2,rep,name=hops,proto3" json:"hops,omitempty"` // list of server IDs for loop detection
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_platform_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_platform_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_platform_health_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckRequest) GetComponents() []string {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *HealthCheckRequest) GetHops() []string {
	if x != nil {
		return x.Hops
	}
	return nil
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`               // e.g. "tcp", "rest", "grpc", "kafka", "s3"
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`               // instance name
	ServerId      *string                `protobuf:"bytes,3,opt,name=serverId,proto3,oneof" json:"serverId,omitempty"` // unique identifier for server/satellite instance
	Status        Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=platform_health.v1.Status" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Details       []*anypb.Any           `protobuf:"bytes,6,rep,name=details,proto3" json:"details,omitempty"`
	Components    []*HealthCheckResponse `protobuf:"bytes,7,rep,name=components,proto3" json:"components,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,8,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_platform_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_platform_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_platform_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HealthCheckResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HealthCheckResponse) GetServerId() string {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return ""
}

func (x *HealthCheckResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNKNOWN
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetDetails() []*anypb.Any {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *HealthCheckResponse) GetComponents() []*HealthCheckResponse {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *HealthCheckResponse) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

var File_proto_platform_health_proto protoreflect.FileDescriptor

const file_proto_platform_health_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/platform_health.proto\x12\x12platform_health.v1\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\"H\n" +
	"\x12HealthCheckRequest\x12\x1e\n" +
	"\n" +
	"components\x18\x01 \x03(\tR\n" +
	"components\x12\x12\n" +
	"\x04hops\x18\x02 \x03(\tR\x04hops\"\xe9\x02\n" +
	"\x13HealthCheckResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\bserverId\x18\x03 \x01(\tH\x00R\bserverId\x88\x01\x01\x122\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1a.platform_health.v1.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12.\n" +
	"\adetails\x18\x06 \x03(\v2\x14.google.protobuf.AnyR\adetails\x12G\n" +
	"\n" +
	"components\x18\a \x03(\v2'.platform_health.v1.HealthCheckResponseR\n" +
	"components\x125\n" +
	"\bduration\x18\b \x01(\v2\x19.google.protobuf.DurationR\bdurationB\v\n" +
	"\t_serverId*D\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aHEALTHY\x10\x01\x12\r\n" +
	"\tUNHEALTHY\x10\x02\x12\x11\n" +
	"\rLOOP_DETECTED\x10\x032d\n" +
	"\x06Health\x12Z\n" +
	"\x05Check\x12&.platform_health.v1.HealthCheckRequest\x1a'.platform_health.v1.HealthCheckResponse\"\x00B9Z7github.com/isometry/platform-health/pkg/platform_healthb\x06proto3"

var (
	file_proto_platform_health_proto_rawDescOnce sync.Once
	file_proto_platform_health_proto_rawDescData []byte
)

func file_proto_platform_health_proto_rawDescGZIP() []byte {
	file_proto_platform_health_proto_rawDescOnce.Do(func() {
		file_proto_platform_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_platform_health_proto_rawDesc), len(file_proto_platform_health_proto_rawDesc)))
	})
	return file_proto_platform_health_proto_rawDescData
}

var file_proto_platform_health_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_platform_health_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_platform_health_proto_goTypes = []any{
	(Status)(0),                 // 0: platform_health.v1.Status
	(*HealthCheckRequest)(nil),  // 1: platform_health.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 2: platform_health.v1.HealthCheckResponse
	(*anypb.Any)(nil),           // 3: google.protobuf.Any
	(*durationpb.Duration)(nil), // 4: google.protobuf.Duration
}
var file_proto_platform_health_proto_depIdxs = []int32{
	0, // 0: platform_health.v1.HealthCheckResponse.status:type_name -> platform_health.v1.Status
	3, // 1: platform_health.v1.HealthCheckResponse.details:type_name -> google.protobuf.Any
	2, // 2: platform_health.v1.HealthCheckResponse.components:type_name -> platform_health.v1.HealthCheckResponse
	4, // 3: platform_health.v1.HealthCheckResponse.duration:type_name -> google.protobuf.Duration
	1, // 4: platform_health.v1.Health.Check:input_type -> platform_health.v1.HealthCheckRequest
	2, // 5: platform_health.v1.Health.Check:output_type -> platform_health.v1.HealthCheckResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_platform_health_proto_init() }
func file_proto_platform_health_proto_init() {
	if File_proto_platform_health_proto != nil {
		return
	}
	file_proto_platform_health_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_platform_health_proto_rawDesc), len(file_proto_platform_health_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_platform_health_proto_goTypes,
		DependencyIndexes: file_proto_platform_health_proto_depIdxs,
		EnumInfos:         file_proto_platform_health_proto_enumTypes,
		MessageInfos:      file_proto_platform_health_proto_msgTypes,
	}.Build()
	File_proto_platform_health_proto = out.File
	file_proto_platform_health_proto_goTypes = nil
	file_proto_platform_health_proto_depIdxs = nil
}
