defaultPlatforms:
  - linux/arm64
  - linux/amd64

builds:
  - id: platform-health-server
    main: ./cmd/server
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
