---
repos:
  - repo: local
    hooks:
      - id: check kubeconform
        name: Kubeconform validation
        entry: bash -c <<<-'
          kubeconform -strict -output json -summary < <(helm template helm/charts) &&
          kubeconform -strict -output json -summary < <(helm template helm/charts --set job.enabled=true) &&
          kubeconform -strict -output json -summary < <(helm template helm/charts --set job.enabled=true --set job.type=CronJob)'
        language: system
        pass_filenames: false
