{{ if not .Values.namespaced }}
---
{{- $role := .Values.role | default dict }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "platform-health.fullname" . }}
  {{- $labels := mergeOverwrite (.Values.common_labels | default dict) ($role.labels | default dict) | toYaml | nindent 4 }}
  labels: {{ $labels }}
  {{- $annotations := mergeOverwrite (.Values.common_annotations | default dict) ($role.annotations | default dict) | toYaml | nindent 4 }}
  annotations: {{ $annotations }}
rules: {{ template "platform-health.rules" . }}
{{- end }}
