---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "platform-health.fullname" . }}
  {{- $configMap := .Values.configMap | default dict }}
  {{- $labels := mergeOverwrite (.Values.common_labels | default dict) ($configMap.labels | default dict) | toYaml | nindent 4 }}
  labels: {{ $labels }}
  {{- $annotations := mergeOverwrite (.Values.common_annotations | default dict) ($configMap.annotations | default dict) | toYaml | nindent 4 }}
  annotations: {{ $annotations }}
data:
  provider-health.yaml: |
  {{- $config := .Values.config | default dict }}
  {{- if $config }}
  {{- range $provider, $targets := $config | default dict }}
    {{ $provider }}:
      {{- $targets | toYaml | nindent 6 }}
  {{ end -}}
  {{- else }}
      {}
  {{- end }}
