---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
data:
  platform-health.yaml: |
    {{- .Values.serverConfig | toYaml | nindent 4 }}
