{{- if .Values.ingress.enabled -}}
---
{{- $ingress := .Values.ingress }}
{{- $serviceName := include "chart.fullname" . }}
{{- $servicePort := .Values.service.port }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- with $ingress.extraLabels -}}{{ toYaml . | nindent 4 }}{{- end }}
  {{- with mergeOverwrite .Values.commonAnnotations $ingress.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  ingressClassName: {{ $ingress.className }}
  rules:
    {{- range $host := $ingress.hosts }}
    - host: {{ tpl $host $ }}
      http:
        paths:
          {{- range $path := $ingress.paths }}
          - path: {{ tpl $path $ }}
            pathType: {{ $ingress.pathType }}
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
          {{- end }}
    {{- end }}
  {{- if $ingress.tls }}
  tls:
    {{- tpl (toYaml $ingress.tls | nindent 4) . }}
  {{- end }}
{{- end }}
