{{ if .Values.service.enabled }}
---
{{- $service := .Values.service | default dict }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "chart.fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- with $service.extraLabels -}}{{ toYaml . | nindent 4 }}{{- end }}
  {{- with mergeOverwrite (.Values.commonAnnotations | default dict) ($service.annotations | default dict) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "matchLabels" . | nindent 4 }}
  ports:
    - port: {{ $service.port }}
      targetPort: {{ .Values.deployment.container.port }}
  type: {{ $service.type }}
{{- end }}
