{{ if .Values.service.enabled }}
---
{{- $service := .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- with $service.extraLabels -}}{{ toYaml . | nindent 4 }}{{- end }}
  {{- with mergeOverwrite .Values.commonAnnotations $service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ $service.port }}
      targetPort: {{ .Values.deployment.container.port }}
  type: {{ $service.type }}
{{- end }}
