{{- if .Values.serviceAccount.create -}}
---
{{- $serviceAccount := .Values.serviceAccount | default dict }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "chart.serviceAccountName" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
  {{- with mergeOverwrite (.Values.commonAnnotations | default dict) ($serviceAccount.annotations | default dict) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
