package main

import (
	"fmt"
	"os"
	"sort"
)

var commonGroupToKinds = map[string][]string{
	"": {
		"configmap",
		"namespace",
		"node",
		"pod",
		"service",
		"secret",
		"persistentvolume",
		"persistentvolumeclaim",
		"storageclass",
	},
	"apps": {
		"deployment",
		"statefulset",
		"daemonset",
		"replicaset",
	},
	"batch": {
		"job",
		"cronjob",
	},
	"cert-manager.io": {
		"clusterissuer",
		"issuer",
		"certificate",
	},
	"networking.k8s.io": {
		"ingressclass",
		"ingress",
		"networkpolicy",
	},
	"gateway.networking.k8s.io": {
		"gatewayclass",
		"gateway",
		"grcproute",
		"httproute",
		"tcproute",
		"tlsroute",
	},
	"policy": {
		"poddisruptionbudget",
		"podsecuritypolicy",
	},
	"argoproj.io": {
		"application",
		"applicationset",
		"appproject",
	},
	"source.toolkit.fluxcd.io": {
		"bucket",
		"externalartifact",
		"gitrepository",
		"helmrepository",
	},
	"kustomize.toolkit.fluxcd.io": {
		"kustomization",
	},
	"helm.toolkit.fluxcd.io": {
		"helmrelease",
	},
}

func generateOutput(groupToKinds map[string][]string) map[string]string {
	output := make(map[string]string)

	for group, kinds := range groupToKinds {
		for _, kind := range kinds {
			output[kind] = group
		}
	}

	return output
}

const fileHeader = `// Code generated by go generate; DO NOT EDIT.
// Amend via commonGroupToKinds in ./common/generator.go
package kubernetes

var commonKindToGroup = map[string]string{`

const fileTrailer = `}`

func writeToFile(filename string, output map[string]string) error {
	file, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer func() { _ = file.Close() }()

	_, _ = fmt.Fprintln(file, fileHeader)
	keys := make([]string, 0, len(output))
	for key := range output {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		_, _ = fmt.Fprintf(file, "\t%q: %q,\n", key, output[key])
	}
	_, _ = fmt.Fprintln(file, fileTrailer)

	return nil
}

func main() {
	output := generateOutput(commonGroupToKinds)

	if err := writeToFile("common_generated.go", output); err != nil {
		panic(err)
	}
}
