package main

import (
	"fmt"
	"os"
	"sort"
)

type GV struct {
	Group   string
	Version string
}

var commonGVToKinds = map[GV][]string{
	{Group: "", Version: "v1"}: {
		"configmap", "cm",
		"namespace", "ns",
		"node", "no",
		"pod", "po",
		"service", "svc",
		"secret", "sec",
		"persistentvolume", "pv",
		"persistentvolumeclaim", "pvc",
		"storageclass", "sc",
	},
	{Group: "apps", Version: "v1"}: {
		"deployment", "deploy",
		"statefulset", "sts",
		"daemonset", "ds",
		"replicaset", "rs",
	},
	{Group: "batch", Version: "v1"}: {
		"job",
		"cronjob",
	},
	{Group: "cert-manager.io", Version: "v1"}: {
		"clusterissuer",
		"issuer",
		"certificate",
	},
	{Group: "networking.k8s.io", Version: "v1"}: {
		"ingressclass",
		"ingress",
		"networkpolicy",
	},
	{Group: "policy", Version: "v1"}: {
		"poddisruptionbudget", "pdb",
		"podsecuritypolicy", "psp",
	},
}

func generateOutput(gvToKinds map[GV][]string) map[string]GV {
	output := make(map[string]GV)

	for key, values := range gvToKinds {
		for _, value := range values {
			output[value] = key
		}
	}

	return output
}

const fileHeader = `// Code generated by go generate; DO NOT EDIT.
// Amend via commonGVToKinds in ./common/generator.go
package kubernetes

var commonKindToGV = map[string]GV{`

const fileTrailer = `}`

func writeToFile(filename string, output map[string]GV) error {
	file, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer file.Close()

	fmt.Fprintln(file, fileHeader)
	keys := make([]string, 0, len(output))
	for key := range output {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		value := output[key]
		fmt.Fprintf(file, "\t%q: {Group: %q, Version: %q},\n", key, value.Group, value.Version)
	}
	fmt.Fprintln(file, fileTrailer)

	return nil
}

func main() {
	output := generateOutput(commonGVToKinds)

	if err := writeToFile("common_generated.go", output); err != nil {
		panic(err)
	}
}
