// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/detail_kstatus.proto

package details

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Detail_KStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Conditions    []*Condition           `protobuf:"bytes,3,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detail_KStatus) Reset() {
	*x = Detail_KStatus{}
	mi := &file_proto_detail_kstatus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detail_KStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detail_KStatus) ProtoMessage() {}

func (x *Detail_KStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detail_kstatus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detail_KStatus.ProtoReflect.Descriptor instead.
func (*Detail_KStatus) Descriptor() ([]byte, []int) {
	return file_proto_detail_kstatus_proto_rawDescGZIP(), []int{0}
}

func (x *Detail_KStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Detail_KStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Detail_KStatus) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type Condition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_proto_detail_kstatus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detail_kstatus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_proto_detail_kstatus_proto_rawDescGZIP(), []int{1}
}

func (x *Condition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Condition) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Condition) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Condition) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_detail_kstatus_proto protoreflect.FileDescriptor

const file_proto_detail_kstatus_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/detail_kstatus.proto\x12\x19platform_health.detail.v1\"\x88\x01\n" +
	"\x0eDetail_KStatus\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12D\n" +
	"\n" +
	"conditions\x18\x03 \x03(\v2$.platform_health.detail.v1.ConditionR\n" +
	"conditions\"i\n" +
	"\tCondition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessageBAZ?github.com/isometry/platform-health/pkg/platform_health/detailsb\x06proto3"

var (
	file_proto_detail_kstatus_proto_rawDescOnce sync.Once
	file_proto_detail_kstatus_proto_rawDescData []byte
)

func file_proto_detail_kstatus_proto_rawDescGZIP() []byte {
	file_proto_detail_kstatus_proto_rawDescOnce.Do(func() {
		file_proto_detail_kstatus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_detail_kstatus_proto_rawDesc), len(file_proto_detail_kstatus_proto_rawDesc)))
	})
	return file_proto_detail_kstatus_proto_rawDescData
}

var file_proto_detail_kstatus_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_detail_kstatus_proto_goTypes = []any{
	(*Detail_KStatus)(nil), // 0: platform_health.detail.v1.Detail_KStatus
	(*Condition)(nil),      // 1: platform_health.detail.v1.Condition
}
var file_proto_detail_kstatus_proto_depIdxs = []int32{
	1, // 0: platform_health.detail.v1.Detail_KStatus.conditions:type_name -> platform_health.detail.v1.Condition
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_detail_kstatus_proto_init() }
func file_proto_detail_kstatus_proto_init() {
	if File_proto_detail_kstatus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_detail_kstatus_proto_rawDesc), len(file_proto_detail_kstatus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_detail_kstatus_proto_goTypes,
		DependencyIndexes: file_proto_detail_kstatus_proto_depIdxs,
		MessageInfos:      file_proto_detail_kstatus_proto_msgTypes,
	}.Build()
	File_proto_detail_kstatus_proto = out.File
	file_proto_detail_kstatus_proto_goTypes = nil
	file_proto_detail_kstatus_proto_depIdxs = nil
}
