// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/detail_dns.proto

package details

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Detail_DNS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Server        string                 `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	QueryType     string                 `protobuf:"bytes,3,opt,name=query_type,json=queryType,proto3" json:"query_type,omitempty"`
	Records       []*DNSRecord           `protobuf:"bytes,4,rep,name=records,proto3" json:"records,omitempty"`
	Dnssec        *DNSSECStatus          `protobuf:"bytes,5,opt,name=dnssec,proto3" json:"dnssec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detail_DNS) Reset() {
	*x = Detail_DNS{}
	mi := &file_proto_detail_dns_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detail_DNS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detail_DNS) ProtoMessage() {}

func (x *Detail_DNS) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detail_dns_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detail_DNS.ProtoReflect.Descriptor instead.
func (*Detail_DNS) Descriptor() ([]byte, []int) {
	return file_proto_detail_dns_proto_rawDescGZIP(), []int{0}
}

func (x *Detail_DNS) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Detail_DNS) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *Detail_DNS) GetQueryType() string {
	if x != nil {
		return x.QueryType
	}
	return ""
}

func (x *Detail_DNS) GetRecords() []*DNSRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *Detail_DNS) GetDnssec() *DNSSECStatus {
	if x != nil {
		return x.Dnssec
	}
	return nil
}

type DNSRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Ttl           uint32                 `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Priority      uint32                 `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Weight        uint32                 `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Port          uint32                 `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	Target        string                 `protobuf:"bytes,7,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSRecord) Reset() {
	*x = DNSRecord{}
	mi := &file_proto_detail_dns_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSRecord) ProtoMessage() {}

func (x *DNSRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detail_dns_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSRecord.ProtoReflect.Descriptor instead.
func (*DNSRecord) Descriptor() ([]byte, []int) {
	return file_proto_detail_dns_proto_rawDescGZIP(), []int{1}
}

func (x *DNSRecord) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DNSRecord) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DNSRecord) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *DNSRecord) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *DNSRecord) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *DNSRecord) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DNSRecord) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type DNSSECStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Authenticated bool                   `protobuf:"varint,2,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSSECStatus) Reset() {
	*x = DNSSECStatus{}
	mi := &file_proto_detail_dns_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSSECStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSSECStatus) ProtoMessage() {}

func (x *DNSSECStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detail_dns_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSSECStatus.ProtoReflect.Descriptor instead.
func (*DNSSECStatus) Descriptor() ([]byte, []int) {
	return file_proto_detail_dns_proto_rawDescGZIP(), []int{2}
}

func (x *DNSSECStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *DNSSECStatus) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

var File_proto_detail_dns_proto protoreflect.FileDescriptor

const file_proto_detail_dns_proto_rawDesc = "" +
	"\n" +
	"\x16proto/detail_dns.proto\x12\x19platform_health.detail.v1\"\xd8\x01\n" +
	"\n" +
	"Detail_DNS\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x16\n" +
	"\x06server\x18\x02 \x01(\tR\x06server\x12\x1d\n" +
	"\n" +
	"query_type\x18\x03 \x01(\tR\tqueryType\x12>\n" +
	"\arecords\x18\x04 \x03(\v2$.platform_health.detail.v1.DNSRecordR\arecords\x12?\n" +
	"\x06dnssec\x18\x05 \x01(\v2'.platform_health.detail.v1.DNSSECStatusR\x06dnssec\"\xa7\x01\n" +
	"\tDNSRecord\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\rR\x03ttl\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\rR\bpriority\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\rR\x06weight\x12\x12\n" +
	"\x04port\x18\x06 \x01(\rR\x04port\x12\x16\n" +
	"\x06target\x18\a \x01(\tR\x06target\"N\n" +
	"\fDNSSECStatus\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12$\n" +
	"\rauthenticated\x18\x02 \x01(\bR\rauthenticatedBAZ?github.com/isometry/platform-health/pkg/platform_health/detailsb\x06proto3"

var (
	file_proto_detail_dns_proto_rawDescOnce sync.Once
	file_proto_detail_dns_proto_rawDescData []byte
)

func file_proto_detail_dns_proto_rawDescGZIP() []byte {
	file_proto_detail_dns_proto_rawDescOnce.Do(func() {
		file_proto_detail_dns_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_detail_dns_proto_rawDesc), len(file_proto_detail_dns_proto_rawDesc)))
	})
	return file_proto_detail_dns_proto_rawDescData
}

var file_proto_detail_dns_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_detail_dns_proto_goTypes = []any{
	(*Detail_DNS)(nil),   // 0: platform_health.detail.v1.Detail_DNS
	(*DNSRecord)(nil),    // 1: platform_health.detail.v1.DNSRecord
	(*DNSSECStatus)(nil), // 2: platform_health.detail.v1.DNSSECStatus
}
var file_proto_detail_dns_proto_depIdxs = []int32{
	1, // 0: platform_health.detail.v1.Detail_DNS.records:type_name -> platform_health.detail.v1.DNSRecord
	2, // 1: platform_health.detail.v1.Detail_DNS.dnssec:type_name -> platform_health.detail.v1.DNSSECStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_detail_dns_proto_init() }
func file_proto_detail_dns_proto_init() {
	if File_proto_detail_dns_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_detail_dns_proto_rawDesc), len(file_proto_detail_dns_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_detail_dns_proto_goTypes,
		DependencyIndexes: file_proto_detail_dns_proto_depIdxs,
		MessageInfos:      file_proto_detail_dns_proto_msgTypes,
	}.Build()
	File_proto_detail_dns_proto = out.File
	file_proto_detail_dns_proto_goTypes = nil
	file_proto_detail_dns_proto_depIdxs = nil
}
